sudo: required
dist: trusty

cache:
  directories:
    - ~/.huchash

language: node_js

node_js:
  - "6"

before_install:
  - sudo add-apt-repository -y ppa:happyuc-project/happyuc
  - sudo apt-get update
  - sudo apt-get install -y ghuc
  - mkdir -p ~/.happyuc
  - mkdir -p ~/.huchash
  - ghuc makedag 0 ~/.huchash

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com

